### ISSUE TITLE
CH4+H2O: DASPK crashes at T>1000K

### ISSUE THREAD

**Issue by cfgoldsmith** [cfgoldsmith/RMG-Py#11]
RMG-Cat has been remarkably stable, except for methane steam reforming about 1000 K.
My input.py parameters are:

```
# Reaction systems
surfaceReactor(
    temperature=(1000,'K'),
    initialPressure=(1.0, 'bar'),
    initialGasMoleFractions={
#        "methyl": 1.0,
        "CH4": 1.0,
        "O2": 0.0,
        "CO2": 0.0,
        "H2O": 1.0,
        "H2": 0.0,
    },
    initialSurfaceCoverages={
        "site": 1.0,
    },
    surfaceVolumeRatio=(1.e5, 'm^-1'),
    surfaceSiteDensity=(2.9e-9, 'mol/cm^2'),
    terminationConversion = { "CH4":0.95,},
    terminationTime=(0.1, 's'),
)

simulator(
    atol=1e-20,
    rtol=1e-12,
)

model(
    toleranceKeepInEdge=0.0,
    toleranceMoveToCore=1e-6,
    toleranceInterruptSimulation=0.1,
    maximumEdgeSpecies=100000
)
```

The resulting error message is:

```
Conducting simulation of reaction system 1...
 DASPK--  AT T (=R1) AND STEPSIZE H (=R2) THE                                    
      In above,  R1 =  0.2164079598224D-12   R2 =  0.1281777033248D-20
 DASPK--  ITERATION MATRIX IS SINGULAR.                                          
Error: Trying to step from time 0.0 to 1e-12
Error: Core species names: ['Ar', 'He', 'Ne', 'N2', 'CH4(1)', 'O2(2)', 'CO2(3)', 'H2O(4)', 'H2(5)', 'CO(6)', 'C2H6(7)', 'CH2O(8)', 'CH3(9)', 'C3H8(10)', 'H(11)', 'C2H5(12)', 'CH3OH(13)', 'site(14)', 'HX(15)', 'CH3X(19)', 'HOX(17)', 'CH2X(20)', 'CHX(21)', 'CX(22)', 'OX(16)', 'OCX(18)', 'COX2(26)', 'CXHO(24)', 'C2H5X(27)', 'CO2X2(25)', 'C2H3OX(38)']
Error: Core species moles: array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   4.99999975e-01,   5.12682963e-46,
        -2.26783830e-21,   5.00000000e-01,   1.29943142e-19,
        -6.91194044e-20,   1.47210983e-15,   2.27764780e-42,
         2.66754216e-15,   3.23767041e-30,   2.34837903e-21,
         9.35169440e-30,   3.23209403e-21,   2.41119638e-01,
         2.53395037e-08,   2.46923157e-08,   1.06500066e-10,
         1.78264647e-11,   1.01418809e-10,   4.98005042e-11,
         7.85466501e-13,   2.16179732e-19,  -7.80727693e-28,
         2.53937230e-29,   1.31677393e-24,   2.26783830e-21,
         2.52125022e-33])
Error: Volume: 0.08314471999999999
Error: Core species net rates: array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,  -1.38171002e+06,   1.42233986e-31,
         6.47358170e-02,  -5.96256551e+03,   2.18433885e-05,
        -8.26417708e+12,   2.44608409e-01,   8.34816004e-28,
         2.95832275e-01,   1.07646652e-15,   2.62443043e-07,
         2.59260608e-15,   5.36980010e-07,  -1.65283570e+13,
         1.43214598e+06,   1.36296194e+06,   5.87547148e+03,
         1.04273200e+03,   9.77012590e+03,   7.93443673e+03,
         8.70939722e+01,   5.93120302e-05,   8.26417708e+12,
         6.32913813e-15,   2.91824890e-10,  -6.47358170e-02,
         9.78728037e-19])
Error: Edge species net rates: array([  6.96788447e-19,   3.81560817e-20,   1.76049712e-25,
         5.28173126e-25,   9.15730735e-16,   4.07178738e-16,
         2.01208825e-08,   5.93144550e-23,   2.04486093e-13,
         1.94887236e-14,   8.84313203e-16,   2.11644081e-23,
         4.85065193e-24,   6.87337517e-26,   9.89056868e-34,
         1.16564596e-33,   3.01696493e-32,   8.59004068e-40,
         1.58246934e-49,   4.37783356e-21,   4.37452335e-30,
         6.18974312e-23,   1.15432232e-32,   2.19193473e-35,
         1.26726177e-38,   9.28549064e-31,   4.98812549e-16,
         4.94475549e-17,   1.36723849e-30,   1.12996635e-25,
         6.78360515e-31,   3.09115071e-33,   1.04717166e-27,
         8.74129260e-27,   1.54974781e-33,   1.06593889e-19,
         1.06593889e-19,   5.48791695e-30,   1.79031835e-34,
         1.68122649e-21,   3.41725490e-36,   2.35416169e-36,
         2.00608838e-29,   9.11537873e-36,   4.14467606e-37,
         5.37118380e-40,   1.67456383e-38,   5.78062016e-42,
         2.09595703e-37,   1.30930686e-43,   8.34798026e-62,
         1.11407105e-51,   1.12272089e-74])
Error: Network leak rates: array([], dtype=float64)
Error: Model core reactions:
Error: Too many to print in detail
Traceback (most recent call last):
  File "../../rmg.py", line 164, in <module>
    rmg.execute(**kwargs)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 578, in execute
    filterReactions=False,
  File "rmgpy/solver/base.pyx", line 348, in rmgpy.solver.base.ReactionSystem.simulate (build/pyrex/rmgpy/solver/base.c:12273)
  File "rmgpy/solver/base.pyx", line 443, in rmgpy.solver.base.ReactionSystem.simulate (build/pyrex/rmgpy/solver/base.c:8703)
pydas.daspk.DASPKError: DASPK returned with an IDID = -8, The matrix of partial derivatives is singular, with the use of direct methods.  Some of your equations may be redundant.  DDASPK cannot solve the problem as stated.  It is possible that the redundant equations could be removed, and then DDASPK could solve the problem.  It is also possible that a solution to your problem either does not exist or is not unique.
```

I will play around with the atol and rtol to see how that fixes things...

**Comment by cfgoldsmith** [comment]
bumping ```atol=1e-18``` seems to have fixed it...
