### ISSUE TITLE
SurfaceArrhenius units fail for training reactions

### ISSUE THREAD

**Issue by cfgoldsmith** [cfgoldsmith/RMG-Py#12]
I tried to implement training reactions for Surface_Abstraction. RMG-Cat crashes with:

Traceback (most recent call last):
  File "../../../rmg.py", line 164, in <module>
    rmg.execute(**kwargs)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 519, in execute
    self.initialize(**kwargs)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 373, in initialize
    self.loadDatabase()
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 318, in loadDatabase
    family.addKineticsRulesFromTrainingSet(thermoDatabase=self.database.thermo)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 966, in addKineticsRulesFromTrainingSet
    ) if isinstance(entry.data, Arrhenius) else deepcopy(data),  # if StickingCoefficient
  File "rmgpy/kinetics/arrhenius.pyx", line 279, in rmgpy.kinetics.arrhenius.ArrheniusEP.__init__ (build/pyrex/rmgpy/kinetics/arrhenius.c:7182)
  File "rmgpy/kinetics/arrhenius.pyx", line 309, in rmgpy.kinetics.arrhenius.ArrheniusEP.A.__set__ (build/pyrex/rmgpy/kinetics/arrhenius.c:7877)
  File "rmgpy/quantity.py", line 739, in rmgpy.quantity.RateCoefficient (build/pyrex/rmgpy/quantity.c:13645)
rmgpy.quantity.QuantityError: Invalid units 'm^2/(mol*s)'.

**Comment by rwest** [comment]
Closed by  https://github.com/rwest/RMG-Py/commit/5b9f028a851b9ec57f886ef1116e39ab18298bf6 and preceding commits (but I don't have write access to this repo so can't close the issue myself?)

Training reactions can now be SurfaceArrhenius, StickingCoefficient, or Arrhenius (gas phase).
When converting to rate rules, these are converted into SurfaceArrheniusBEP, StickingCoefficientBEP, and ArrheniusEP rules respectively. The latter three have alpha and E0 instead of Ea  (because Ea = alpha*∆Hrxn + E0). (They also force the T0 to be 1K).
