### ISSUE TITLE
Surface_Dissociation family doesn't recognize Triple bond

### ISSUE THREAD

**Issue by cfgoldsmith** [cfgoldsmith/RMG-Py#14]
In the process of building the training data for Surface_Dissociation, I added the reaction:

CH* + Ni = C* + H* (Reaction 19 in the Deutschmann mechanism).

At first, it threw up the error:

```
Traceback (most recent call last):
  File "../../../rmg.py", line 164, in <module>
    rmg.execute(**kwargs)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 519, in execute
    self.initialize(**kwargs)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 373, in initialize
    self.loadDatabase()
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 318, in loadDatabase
    family.addKineticsRulesFromTrainingSet(thermoDatabase=self.database.thermo)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1025, in addKineticsRulesFromTrainingSet
    template = self.getReactionTemplate(item)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1907, in getReactionTemplate
    return self.groups.getReactionTemplate(reaction)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/groups.py", line 163, in getReactionTemplate
    raise UndeterminableKineticsError(reaction, message=msg)
rmgpy.data.kinetics.common.UndeterminableKineticsError: (Reaction(reactants=[Molecule(SMILES="C~[Ni]"), Molecule(SMILES="[Ni]")], products=[Molecule(SMILES="C#[Ni]"), Molecule(SMILES="[Ni]")]), 'Kinetics could not be determined. Unable to find matching template for reaction <Molecule "C~[Ni]"> + <Molecule "[Ni]"> <=> <Molecule "C#[Ni]"> + <Molecule "[Ni]"> in reaction family <KineticsGroups "Surface_Dissociation/groups">.Trying to match [<Entry index=1 label="Combined">, <Entry index=2 label="VacantSite">] but matched []')
```

I then modified the reaction template to include the possibility of a carbon that is triple bonded:

```
1 *1 R  u0 {2,S} {3,[S,D,T]}
2 *2 R  u0 {1,S}
3 *3 Xo u0 {1,[S,D,T]}
```

But now RMG-Cat gives me:

```
Traceback (most recent call last):
  File "../../../rmg.py", line 164, in <module>
    rmg.execute(**kwargs)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 519, in execute
    self.initialize(**kwargs)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 373, in initialize
    self.loadDatabase()
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 300, in loadDatabase
    depository = False, # Don't bother loading the depository information, as we don't use it
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/rmg.py", line 101, in load
    kineticsDepositories
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/rmg.py", line 164, in loadKinetics
    depositories=kineticsDepositories
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/database.py", line 108, in load
    self.loadFamilies(os.path.join(path, 'families'), families, depositories)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/database.py", line 195, in loadFamilies
    family.load(familyPath, self.local_context, self.global_context, depositoryLabels=depositories)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 550, in load
    self.forwardTemplate.products = self.generateProductTemplate(self.forwardTemplate.reactants)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 848, in generateProductTemplate
    productStructure = self.applyRecipe(reactantStructure, forward=True, unique=False)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1114, in applyRecipe
    self.forwardRecipe.applyForward(reactantStructure, unique)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 294, in applyForward
    return self.__apply(struct, True, unique)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 232, in __apply
    bond.applyAction(['CHANGE_BOND', label1, info, label2])
  File "rmgpy/molecule/group.py", line 466, in rmgpy.molecule.group.GroupBond.applyAction (build/pyrex/rmgpy/molecule/group.c:9951)
  File "rmgpy/molecule/group.py", line 474, in rmgpy.molecule.group.GroupBond.applyAction (build/pyrex/rmgpy/molecule/group.c:9819)
  File "rmgpy/molecule/group.py", line 455, in rmgpy.molecule.group.GroupBond.__changeBond (build/pyrex/rmgpy/molecule/group.c:9400)
rmgpy.molecule.group.ActionError: Unable to update GroupBond due to CHANGE_BOND action: Invalid bond order "T" in set ['S', 'D', 'T']".
```

**Comment by rwest** [comment]
Can you push a database that causes this crash? I can't reproduce with the current head of both 'cat' branches.

**Comment by cfgoldsmith** [comment]
Just pushed the database changes: 
d45418703751cfe0f257bc97f635535d5c0efbcd

**Comment by cfgoldsmith** [comment]
Works for me.
