### ISSUE TITLE
How to install RMG-Cat branch alongside another RMG-Py

### ISSUE THREAD

**Issue by rwest** [cfgoldsmith/RMG-Py#20]
You will want to globally swap /rwest/cfgoldsmith/ and /richard/franklin/, and tweak another few settings according to your local setup, but this is a cleaned up version of what I have got to work:
```
$ cd ~
$ cd Code
$ mkdir Cat
$ cd Cat
$ git clone --branch cat --origin github git@github.com:rwest/RMG-database
$ cd RMG-database/
$ git remote add franklin git@github.com:cfgoldsmith/RMG-database
$ git fetch franklin
$ cd ..
$ git clone --branch cat --origin github git@github.com:rwest/RMG-Py
$ cd RMG-Py
$ git remote add franklin git@github.com:cfgoldsmith/RMG-Py
$ git fetch franklin
## if it exists, remove your global rmgrc setting
$ rm $HOME/.rmg/rmgrc 
## if you just want to use the RMG-database that lives alongside your RMG-Py then the following line is not needed:
$ echo "database.directory : $HOME/Code/Cat/RMG-database/input" >> rmgpy/rmgrc
$ cat rmgpy/rmgrc
$ source activate rmg6  # or whatever your RMG anaconda environment is, eg. rmg_env 
$ make -j4
$ python rmg.py testing/surface/input.py 
## Carefully read the first two lines of output. Should say which database its using and where it found that setting.
## Then check it works from here too:
$ cd testing/surface/
$ python ../../rmg.py input.py 
## Carefully read the first two lines of output.
```

Then set up separate projects in PyCharm.

For some things you may want `$RMGpy` to point to your RMG-Py folder, eg.
```
$ export RMGpy=$HOME/Code/RMG-Py
```
or
```
$ export RMGpy=$HOME/Code/Cat/RMG-Py
```
but a quick search suggests that's perhaps I only do this for convenience in my ancillary scripts etc and nothing in the RMG core depends on this variable.

**Comment by rwest** [comment]
Just realized the line 
```
$ echo "database.directory : $HOME/Code/Cat/RMG-database/input" >> rmgpy/rmgrc
```
is not needed, because it will default to `../RMG-database/input` relative to the RMG-Py source code that is being run, *as long as* you haven't overwritten this with a setting in `~/.rmg/rmgrc` (which I had). 
So as long as you do
```
$ rm $HOME/.rmg/rmgrc  
```
to clear that out then running parallel installations should be pretty trivial as long as `RMG-Py` and `RMG-database` live alongside each other.

**Comment by cfgoldsmith** [comment]
I followed along, but the code threw up an error. 

```
Traceback (most recent call last):
  File "../../rmg.py", line 164, in <module>
    rmg.execute(**kwargs)
  File "/Users/claudefranklingoldsmith/code/Cat/RMG-Py/rmgpy/rmg/main.py", line 655, in execute
    bimolecularReact=self.bimolecularReact)
  File "/Users/claudefranklingoldsmith/code/Cat/RMG-Py/rmgpy/rmg/model.py", line 793, in enlarge
    spec.getThermoData(database, quantumMechanics=self.quantumMechanics)
  File "/Users/claudefranklingoldsmith/code/Cat/RMG-Py/rmgpy/rmg/model.py", line 93, in getThermoData
    self.generateThermoData(database, thermoClass, quantumMechanics)
  File "/Users/claudefranklingoldsmith/code/Cat/RMG-Py/rmgpy/rmg/model.py", line 113, in generateThermoData
    thermo0 = database.thermo.getThermoData(self, trainingSet=None, quantumMechanics=quantumMechanics)
  File "/Users/claudefranklingoldsmith/code/Cat/RMG-Py/rmgpy/data/thermo.py", line 735, in getThermoData
    thermo0 = self.getThermoDataForSurfaceSpecies(species, quantumMechanics=quantumMechanics)
  File "/Users/claudefranklingoldsmith/code/Cat/RMG-Py/rmgpy/data/thermo.py", line 898, in getThermoDataForSurfaceSpecies
    self.__addGroupThermoData(thermo, self.groups['adsorption'], molecule, {})
  File "/Users/claudefranklingoldsmith/code/Cat/RMG-Py/rmgpy/data/thermo.py", line 1338, in __addGroupThermoData
    raise KeyError('Node not found in thermo database for atom {0} in molecule {1}.'.format(atom, molecule))
KeyError: 'Node not found in thermo database for atom {} in molecule <Molecule "[O][Ni]">.'
```

Not sure if you get the same one or not.

**Comment by rwest** [comment]
Are you up to date with my cat branch on both Rmg and database?

**Comment by rwest** [comment]
I think you hit issue #19.

**Comment by cfgoldsmith** [comment]
Fixed it. I didn't realize my cat was not up-to-date with yours...
