### ISSUE TITLE
Cantera conversion expects transport data for surface site 

### ISSUE THREAD

**Issue by rwest** [cfgoldsmith/RMG-Py#28]
I think our test job ran to almost completion, and then at the end when trying to make cantera files,....

```python
Traceback (most recent call last):
  File "../../rmg.py", line 173, in <module>
    main()
  File "../../rmg.py", line 158, in main
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/Users/rwest/anaconda/envs/rmgcat3/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/Users/rwest/anaconda/envs/rmgcat3/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 787, in execute
    self.generateCanteraFiles(os.path.join(self.outputDirectory, 'chemkin', 'chem.inp'))
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 1041, in generateCanteraFiles
    parser.convertMech(chemkinFile, transportFile=transportFile, outName=outName, quiet=True, permissive=True, **kwargs)
  File "/Users/rwest/anaconda/envs/rmgcat3/lib/python2.7/site-packages/cantera/ck2cti.py", line 2212, in convertMech
    raise InputParseError("No transport data for species '{0}'.".format(s))
cantera.ck2cti.InputParseError: No transport data for species 'site(18)'.
(rmgcat3) RichardsMacBookPro13:surface rwest$ 
```

This is part of `generateCanteraFiles`. Cantera's ck2cti expects transport data, which we don't have for vacant surface sites.

**Comment by cfgoldsmith** [comment]
I'm pretty sure it is possible to omit the --transport=tran.dat flag in ck2cti?  I've used ck2cti on mechanisms that lacked transport data before for gas phase.

**Comment by rwest** [comment]
Good idea, @cfgoldsmith .
With that in a try/catch block (https://github.com/rwest/RMG-Py/commit/e23abde561d26f4f2d88641b2529a9f48940e72f )
it now does this
```
Generating plots of execution statistics...

Error: Error converting to Cantera format.
Traceback (most recent call last):
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 1045, in generateCanteraFiles
    parser.convertMech(chemkinFile, transportFile=transportFile, outName=outName, quiet=True, permissive=True, **kwargs)
  File "/Users/rwest/anaconda/envs/rmgcat3/lib/python2.7/site-packages/cantera/ck2cti.py", line 2212, in convertMech
    raise InputParseError("No transport data for species '{0}'.".format(s))
InputParseError: No transport data for species 'site(18)'.
Trying again without transport data file.
Warning: Found additional declaration of species Ar
...
```
then continues with its second attempt, which works fine (until some other bug later).
