### ISSUE TITLE
AtomTypeError in new Pt thermo library bidentate OO 

### ISSUE THREAD

**Issue by rwest** [cfgoldsmith/RMG-Py#38]
```
Loading thermodynamics library from surfaceThermoPt.py in /Users/rwest/Code/Cat/RMG-database/input/thermo/libraries...
Error: Could not update atomtypes for this molecule:
1 X u0 p0 c0 {2,S} {3,S}
2 X u0 p0 c0 {1,S} {4,S}
3 O u0 p2 c0 {1,S} {4,S}
4 O u0 p2 c0 {2,S} {3,S}

Error: Error while reading database '/Users/rwest/Code/Cat/RMG-database/input/thermo/libraries/surfaceThermoPt.py'.
Traceback (most recent call last):
  File "/Users/rwest/Code/Cat/RMG-Py/rmg.py", line 173, in <module>
    main()
  File "/Users/rwest/Code/Cat/RMG-Py/rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 556, in execute
    self.initialize(**kwargs)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 418, in initialize
    self.loadDatabase()
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 322, in loadDatabase
    depository = False, # Don't bother loading the depository information, as we don't use it
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/rmg.py", line 96, in load
    self.loadThermo(os.path.join(path, 'thermo'), thermoLibraries, depository)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/rmg.py", line 118, in loadThermo
    self.thermo.load(path, thermoLibraries, depository)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/thermo.py", line 804, in load
    self.loadLibraries(os.path.join(path, 'libraries'), libraries)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/thermo.py", line 842, in loadLibraries
    library.load(os.path.join(path, f), self.local_context, self.global_context)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/base.py", line 224, in load
    exec f in global_context, local_context
  File "/Users/rwest/Code/Cat/RMG-database/input/thermo/libraries/surfaceThermoPt.py", line 162, in <module>
    Tmax = (2000.0, 'K'),
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/thermo.py", line 603, in loadEntry
    molecule = Molecule().fromAdjacencyList(molecule)
  File "rmgpy/molecule/molecule.py", line 1478, in rmgpy.molecule.molecule.Molecule.fromAdjacencyList
  File "rmgpy/molecule/molecule.py", line 1487, in rmgpy.molecule.molecule.Molecule.fromAdjacencyList
  File "rmgpy/molecule/molecule.py", line 1210, in rmgpy.molecule.molecule.Molecule.updateAtomTypes
  File "rmgpy/molecule/molecule.py", line 1205, in rmgpy.molecule.molecule.Molecule.updateAtomTypes
  File "rmgpy/molecule/atomtype.py", line 726, in rmgpy.molecule.atomtype.getAtomType
  File "rmgpy/molecule/atomtype.py", line 762, in rmgpy.molecule.atomtype.getAtomType
rmgpy.exceptions.AtomTypeError: Unable to determine atom type for atom X, which has 2 single bonds, 0 double bonds to C, 0 double bonds to O, 0 double bonds to S, 0 triple bonds, 0 benzene bonds, 0 lone pairs, and 0 charge.
```

**Comment by rwest** [comment]
I got rid of this problem by removing the single bond between the two adsorbate sites.

Unfortunately, @mazeau found that adding the single bond made the pictures much much better.
I wonder if we should just hack the picture-drawing code, or if we actually should represent 
the X sites as being covalently bonded, in terms of graph matching, etc.

For now I removed the bonds and it seems to work:
https://github.com/rwest/RMG-database/commit/b0fb89050806251b9858e4f62d377a912b2b8bc2
