### ISSUE TITLE
Problem with three reactants after recent merge

### ISSUE THREAD

**Issue by rwest** [cfgoldsmith/RMG-Py#44]
Now that the input file `testing/surface/ch4_o2/input.py`
contains the line `kineticsFamilies = ['surface','default'],`
running it fails like this:
```
Problem family: Surface_Adsorption_Dissociative
Problem reactants: (Molecule(SMILES="C"), Molecule(SMILES="C"), Molecule(SMILES="C"))
Traceback (most recent call last):
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/scoop_framework/util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/react.py", line 75, in reactSpecies
    reactions = getDB('kinetics').generate_reactions_from_families(speciesTuple)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/database.py", line 519, in generate_reactions_from_families
    reaction_list.extend(self.react_molecules(combo, products=products, only_families=only_families, prod_resonance=resonance))
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/database.py", line 545, in react_molecules
    reaction_list.extend(family.generateReactions(molecules, products=products, prod_resonance=prod_resonance))
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/family.py", line 1634, in generateReactions
    self.__generateReactions(reactants, products=products, forward=True, prod_resonance=prod_resonance))
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/family.py", line 1985, in __generateReactions
    raise NotImplementedError("Three reactants not containing two surface sites")
NotImplementedError: Three reactants not containing two surface sites
```

**Comment by rwest** [comment]
Fixed in cf42d3a36ccce80b29f8178bdeed76ec9f6cdc5f
