### ISSUE TITLE
Pruning crashes with surface reactions

### ISSUE THREAD

**Issue by kblondal** [cfgoldsmith/RMG-Py#64]
I am trying to generate a mechanism for propane catalytic combustion with equivalence ratio 0.5 (2% propane, 20% O2, 78% N2 inlet composition), using a reactor at 1500K. The run crashes with the following end message:

```
    After model enlargement:
    The model core has 134 species and 2064 reactions
    The model edge has 6474 species and 23086 reactions


Saving current model core to Chemkin file...
Chemkin file contains 1879 reactions.
Chemkin file contains 214 reactions.
Saving annotated version of Chemkin files...
Chemkin file contains 1879 reactions.
Chemkin file contains 214 reactions.
Saving current model core to HTML file...
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 00:01:48:30
    Memory used: 1699.19 MB

Attempting to prune...
Pruning 6348 species whose rate ratios against characteristic rate did not exceed the minimum threshold of 0.05
Pruning species Ar(22)
Pruning species CH3CHNH2(136)
Pruning species CH2NH(112)

[more pruning...]

Garbage collector: collected 464089 objects.
Conducting simulation of reaction system 1...
Error: Model core reactions:
Error: Too many to print in detail
Making seed mechanism...
Traceback (most recent call last):
  File "rmg.py", line 173, in <module>
    main()
  File "rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/kblondal/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 745, in execute
    conditions = self.rmg_memories[index].get_cond()
  File "rmgpy/solver/base.pyx", line 564, in rmgpy.solver.base.ReactionSystem.simulate
    cpdef simulate(self, list coreSpecies, list coreReactions, list edgeSpecies,
  File "rmgpy/solver/base.pyx", line 663, in rmgpy.solver.base.ReactionSystem.simulate
    self.initializeModel(coreSpecies, coreReactions, edgeSpecies, edgeReactions, surfaceSpecies, surfaceReactions,
  File "rmgpy/solver/surface.pyx", line 171, in rmgpy.solver.surface.SurfaceReactor.initializeModel
    reactionsOnSurface[index] = 1
IndexError: Out of bounds on buffer access (axis 0)
```

What could be causing this?

**Comment by rwest** [comment]
We have a bug when pruning models with surface reactions?  Possibly the list of which reactions are surface reactions is not updated when the reactions are deleted. 

Not unlikely. 

Try turning off pruning.
