### ISSUE TITLE
Pressure-dependent reaction libraries not compatible with P-independent RMG-cat?

### ISSUE THREAD

**Issue by rwest** [cfgoldsmith/RMG-Py#75]
In group meeting @mazeau is talking about something to do with pressure dependent libraries not working in RMG-Cat. She will update this issue with details.

**Comment by mazeau** [comment]
this is the input

```database(
    thermoLibraries=['surfaceThermoPt', 'primaryThermoLibrary', 'thermo_DFT_CCSDTF12_BAC','DFT_QCI_thermo'],
    reactionLibraries = ['Glarborg/C1','Surface/CPOX_Pt/Deutschmann2006','BurkeH2O2inArHe','GRI-HCO','Glarborg/C0'],
    seedMechanisms = [],
    kineticsDepositories = ['training'],
    kineticsFamilies =['surface','default'],
    kineticsEstimator = 'rate rules',
    bindingEnergies = { # default values for Pt(111)
                       'C':(-6.750, 'eV/molecule'),
                       'O':(-3.586, 'eV/molecule'),
                       'N':(-4.352, 'eV/molecule'),
                       'H':(-2.479, 'eV/molecule'),
                       }
)
```
and this is the error
```
Traceback (most recent call last):
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmg.py", line 173, in <module>
    main()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmg.py", line 158, in main
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/home/mazeau.e/anaconda2/envs/rmg_env3/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/home/mazeau.e/anaconda2/envs/rmg_env3/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/rmg/main.py", line 947, in execute
    self.check_model()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/rmg/main.py", line 994, in check_model
    p_min=self.Pmin, p_max=self.Pmax)
  File "rmgpy/reaction.py", line 1206, in rmgpy.reaction.Reaction.check_collision_limit_violation
  File "rmgpy/reaction.py", line 1239, in rmgpy.reaction.Reaction.check_collision_limit_violation
  File "rmgpy/kinetics/arrhenius.pyx", line 505, in rmgpy.kinetics.arrhenius.PDepArrhenius.getRateCoefficient
  File "rmgpy/kinetics/arrhenius.pyx", line 515, in rmgpy.kinetics.arrhenius.PDepArrhenius.getRateCoefficient
ValueError: No pressure specified to pressure-dependent PDepArrhenius.getRateCoefficient().
```

**Comment by rwest** [comment]
So this looks like it is a duplicate of #61 which is on the list of things to address at the hackathon tomorrow.  Not an issue with building the model, just with checking it at the end (so the models you built with this, Emily, should be fine).
